-- NOBOCHITRO catalogue expansion: 100 well-known films for UI testing.
-- Run after seed_data.sql. Run it only once for a database, since it uses
-- seq_movie.NEXTVAL to assign new IDs.
INSERT ALL
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL, 'The Shawshank Redemption', 1994, 142, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 1, 'The Godfather', 1972, 175, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 2, 'The Dark Knight', 2008, 152, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 3, 'Pulp Fiction', 1994, 154, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 4, 'The Lord of the Rings: The Return of the King', 2003, 201, 'English', 'New Zealand')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 5, 'Schindler''s List', 1993, 195, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 6, 'The Lord of the Rings: The Fellowship of the Ring', 2001, 178, 'English', 'New Zealand')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 7, 'Fight Club', 1999, 139, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 8, 'Forrest Gump', 1994, 142, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 9, 'The Matrix', 1999, 136, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 10, 'Goodfellas', 1990, 145, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 11, 'Se7en', 1995, 127, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 12, 'The Silence of the Lambs', 1991, 118, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 13, 'Saving Private Ryan', 1998, 169, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 14, 'Interstellar', 2014, 169, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 15, 'Spirited Away', 2001, 125, 'Japanese', 'Japan')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 16, 'City of God', 2002, 130, 'Portuguese', 'Brazil')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 17, 'Life Is Beautiful', 1997, 116, 'Italian', 'Italy')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 18, 'The Green Mile', 1999, 189, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 19, 'Gladiator', 2000, 155, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 20, 'The Departed', 2006, 151, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 21, 'Whiplash', 2014, 106, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 22, 'The Prestige', 2006, 130, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 23, 'The Lion King', 1994, 88, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 24, 'Back to the Future', 1985, 116, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 25, 'Alien', 1979, 117, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 26, 'Psycho', 1960, 109, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 27, 'The Pianist', 2002, 150, 'English', 'France')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 28, 'The Truman Show', 1998, 103, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 29, 'The Usual Suspects', 1995, 106, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 30, 'American History X', 1998, 119, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 31, 'Casablanca', 1942, 102, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 32, 'Modern Times', 1936, 87, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 33, 'Raiders of the Lost Ark', 1981, 115, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 34, 'Rear Window', 1954, 112, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 35, 'Cinema Paradiso', 1988, 155, 'Italian', 'Italy')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 36, 'Apocalypse Now', 1979, 147, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 37, 'Django Unchained', 2012, 165, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 38, 'WALL-E', 2008, 98, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 39, 'The Lives of Others', 2006, 137, 'German', 'Germany')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 40, 'Memento', 2000, 113, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 41, 'Sunset Boulevard', 1950, 110, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 42, 'Paths of Glory', 1957, 88, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 43, 'The Great Dictator', 1940, 125, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 44, 'Avengers: Endgame', 2019, 181, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 45, 'Spider-Man: Into the Spider-Verse', 2018, 117, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 46, 'Coco', 2017, 105, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 47, 'Your Name', 2016, 106, 'Japanese', 'Japan')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 48, 'The Intouchables', 2011, 112, 'French', 'France')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 49, 'Incendies', 2010, 131, 'French', 'Canada')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 50, 'Toy Story 3', 2010, 103, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 51, 'Up', 2009, 96, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 52, 'The Dark Knight Rises', 2012, 164, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 53, 'Inglourious Basterds', 2009, 153, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 54, 'Eternal Sunshine of the Spotless Mind', 2004, 108, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 55, 'Amelie', 2001, 122, 'French', 'France')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 56, 'Snatch', 2000, 104, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 57, 'Requiem for a Dream', 2000, 102, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 58, 'The Sixth Sense', 1999, 107, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 59, 'L.A. Confidential', 1997, 138, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 60, 'Trainspotting', 1996, 94, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 61, 'Before Sunrise', 1995, 101, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 62, 'The Nightmare Before Christmas', 1993, 76, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 63, 'Reservoir Dogs', 1992, 99, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 64, 'Terminator 2: Judgment Day', 1991, 137, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 65, 'Dead Poets Society', 1989, 128, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 66, 'Die Hard', 1988, 132, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 67, 'Full Metal Jacket', 1987, 116, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 68, 'Platoon', 1986, 120, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 69, 'The Thing', 1982, 109, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 70, 'Raging Bull', 1980, 129, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 71, 'Star Wars', 1977, 121, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 72, 'Taxi Driver', 1976, 114, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 73, 'Jaws', 1975, 124, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 74, 'The Godfather Part II', 1974, 202, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 75, 'Chinatown', 1974, 130, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 76, 'The Exorcist', 1973, 122, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 77, 'A Clockwork Orange', 1971, 136, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 78, '2001: A Space Odyssey', 1968, 149, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 79, 'The Good, the Bad and the Ugly', 1966, 161, 'Italian', 'Italy')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 80, 'Dr. Strangelove', 1964, 95, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 81, 'To Kill a Mockingbird', 1962, 129, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 82, 'Lawrence of Arabia', 1962, 228, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 83, 'The Apartment', 1960, 125, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 84, 'North by Northwest', 1959, 136, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 85, 'Vertigo', 1958, 128, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 86, '12 Angry Men', 1957, 96, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 87, 'Singin'' in the Rain', 1952, 103, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 88, 'All About Eve', 1950, 138, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 89, 'The Third Man', 1949, 104, 'English', 'UK')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 90, 'Bicycle Thieves', 1948, 89, 'Italian', 'Italy')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 91, 'It''s a Wonderful Life', 1946, 130, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 92, 'Double Indemnity', 1944, 107, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 93, 'The Kid', 1921, 68, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 94, 'Dune: Part Two', 2024, 166, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 95, 'Oppenheimer: The Story', 2023, 180, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 96, 'Everything Everywhere All at Once', 2022, 139, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 97, 'Top Gun: Maverick', 2022, 130, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 98, 'The Batman', 2022, 176, 'English', 'USA')
  INTO Movie (MovieID, Title, ReleaseYear, Runtime, Language, Country) VALUES (seq_movie.NEXTVAL + 99, 'Spider-Man: No Way Home', 2021, 148, 'English', 'USA')
SELECT 1 FROM dual;

-- INSERT ALL evaluates NEXTVAL only once. Advance the sequence past the 100 IDs
-- assigned above so future inserts cannot collide with this seed data.
ALTER SEQUENCE seq_movie INCREMENT BY 100;
SELECT seq_movie.NEXTVAL FROM dual;
ALTER SEQUENCE seq_movie INCREMENT BY 1;

COMMIT;
