import { useEffect, useState } from 'react';
import Header from '../components/Header';
import { getPassport, getUserChallenges, joinChallenge, listChallenges } from '../api/movies';
import './JourneyPages.css';

export default function PassportPage({ user, onLogout, onNavigate }) {
  const [passport, setPassport] = useState(null); const [challenges, setChallenges] = useState([]); const [joined, setJoined] = useState([]); const [search, setSearch] = useState('');
  async function load() { const data = await Promise.all([getPassport(user.userId), listChallenges(), getUserChallenges(user.userId)]); setPassport(data[0]); setChallenges(data[1]); setJoined(data[2]); }
  useEffect(() => { load().catch(() => {}); }, []);
  async function join(id) { try { await joinChallenge(id); await load(); } catch { } }
  if (!passport) return <div className="journey-page"><Header searchValue={search} onSearchChange={setSearch} onLogout={onLogout} activePage="passport" onNavigate={onNavigate} /><p className="profile-status">Opening your passport…</p></div>;
  const current = challenges[0]; const progress = joined.find((x) => x.CHALLENGEID === current?.CHALLENGEID);
  return <div className="journey-page"><Header searchValue={search} onSearchChange={setSearch} onLogout={onLogout} activePage="passport" onNavigate={onNavigate} /><main className="journey-wrap"><header className="journey-hero passport-hero"><p>NOBOCHITRO MOVIE PASSPORT</p><h1>Your journey through cinema.</h1><span>Every movie takes you somewhere.</span></header><section className="passport-card"><div className="passport-id"><span className="passport-avatar">{(user.displayName || user.username).charAt(0)}</span><div><p>PASSENGER</p><h2>{user.displayName || user.username}</h2><small>Member since {new Date().getFullYear()}</small></div></div><div className="passport-stats"><div><b>🎬 {passport.totalWatched}</b><span>Movies watched</span></div><div><b>🌎 {passport.countriesExplored}</b><span>Countries</span></div><div><b>🗣 {passport.languagesExplored}</b><span>Languages</span></div><div><b>⭐ {passport.averageRating || '–'}</b><span>Avg. rating</span></div></div><div className="passport-details"><span>Favourite genre <strong>{passport.favoriteGenre || 'Still discovering'}</strong></span><span>Favourite director <strong>{passport.favoriteDirector || 'Still discovering'}</strong></span><span>Most rewatched <strong>{passport.mostWatchedMovie?.title || 'No repeat visits yet'}</strong></span></div></section>{current && <section className="weekly-challenge"><p>THIS WEEK’S CHALLENGE</p><h2>{current.TITLE}</h2><span>{current.DESCRIPTION}</span>{progress ? <><div className="challenge-progress"><i style={{ width: `${Math.min(100, (progress.CURRENTPROGRESS / current.TARGETCOUNT) * 100)}%` }} /></div><strong>{progress.CURRENTPROGRESS} / {current.TARGETCOUNT} complete · +{current.XPREWARD} XP</strong></> : <button type="button" onClick={() => join(current.CHALLENGEID)}>Join challenge · +{current.XPREWARD} XP</button>}</section>}</main></div>;
}
